---

- name: tap homebrew/cask-versions
  homebrew_tap: tap=homebrew/cask-versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    - watch
    - rsync

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - sequel-pro
